### ISSUE TITLE
Process Event

### ISSUE THREAD

**Issue by ghost** [CorrM/Unreal-Finder-Tool#29]
![image](https://user-images.githubusercontent.com/16446639/59315063-62bdfc80-8cb8-11e9-805e-defaa6dccab1.png)
It doesn't generate this part here.

**Comment by coinhivelife** [comment]
I have the same exact issue.

**Comment by corrm** [comment]
for now u can go to `CoreUObject_classes.h` and add empty function called `ProcessEvent`.
this fix until i support `auto fetching ProcessEvent`.
![2019-06-12_14-24-53](https://user-images.githubusercontent.com/5868825/59351125-f544b700-8d1d-11e9-81c7-8b06a46dd11f.png)

NOTE:
That's will fix the error when build, NOT fix the problem since you can add the really `ProcessEvent` by your self or just wait to support it.

**Comment by johmarjac** [comment]
@CorrM Normally ProcessEvent is at index 64 in UObject::Vtable, right? Cant you just simply grab that address and maybe do some other checks to see if it is the correct function? However there are games (for example MORDHAU) where it is at another index (65 for MORDHAU), so in that (I would say) rare case, someone still needs to be doing some self searching. Just a thought tho :)

**Comment by corrm** [comment]
@johmarjac as u say i need to make a dynamic method to find it, anyway the version 3.1.0 will support `ProceesEvent`.

and add me in discord `CorrM#0664`

**Comment by corrm** [comment]
Supported, will be in version 3.1.0
